# Before we start

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
pd.set_option('display.width', 180)


<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

In [ ]:
from google.colab import output
from IPython.display import Javascript

def resize_colab_cell():
    display(Javascript('google.colab.output.setIframeHeight(0, true, {maxHeight: 5000})'))

get_ipython().events.register('pre_run_cell', resize_colab_cell)


<IPython.core.display.Javascript object>

In [5]:
import pandas as pd

# Replace 'path/to/homelessness.csv' with the path to your CSV file
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/WK10-Pandas Learner/Resources/data.csv')
# Print the first 5 rows of the DataFrame
print(df.head())


   Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0


index_col is a parameter of the pandas.read_csv function that specifies which column of the CSV file to use as the row labels of the DataFrame1. If index_col is set to 0, it means that the first column of the CSV file will be used as the row labels. For example, if the CSV file looks like this:

As we do not need to do it for our data so we shall remove the index_col parameter but we shall need to use it later.

* * *

#Data Cleaning
-------------

Data cleaning means fixing bad data in your data set.

Bad data could be:

*   Empty cells
*   Data in wrong format
*   Wrong data
*   Duplicates

In this tutorial you will learn how to deal with all of them.

* * *

Our Data Set
------------
```
In the next chapters we will use this data set:

      Duration          Date  Pulse  Maxpulse  Calories
  0         60  '2020/12/01'    110       130     409.1
  1         60  '2020/12/02'    117       145     479.0
  2         60  '2020/12/03'    103       135     340.0
  3         45  '2020/12/04'    109       175     282.4
  4         45  '2020/12/05'    117       148     406.0
  5         60  '2020/12/06'    102       127     300.0
  6         60  '2020/12/07'    110       136     374.0
  7        450  '2020/12/08'    104       134     253.3
  8         30  '2020/12/09'    109       133     195.1
  9         60  '2020/12/10'     98       124     269.0
  10        60  '2020/12/11'    103       147     329.3
  11        60  '2020/12/12'    100       120     250.7
  12        60  '2020/12/12'    100       120     250.7
  13        60  '2020/12/13'    106       128     345.3
  14        60  '2020/12/14'    104       132     379.3
  15        60  '2020/12/15'     98       123     275.0
  16        60  '2020/12/16'     98       120     215.2
  17        60  '2020/12/17'    100       120     300.0
  18        45  '2020/12/18'     90       112       NaN
  19        60  '2020/12/19'    103       123     323.0
  20        45  '2020/12/20'     97       125     243.0
  21        60  '2020/12/21'    108       131     364.2
  22        45           NaN    100       119     282.0
  23        60  '2020/12/23'    130       101     300.0
  24        45  '2020/12/24'    105       132     246.0
  25        60  '2020/12/25'    102       126     334.5
  26        60    2020/12/26    100       120     250.0
  27        60  '2020/12/27'     92       118     241.0
  28        60  '2020/12/28'    103       132       NaN
  29        60  '2020/12/29'    100       132     280.0
  30        60  '2020/12/30'    102       129     380.3
  31        60  '2020/12/31'     92       115     243.0
```
The data set contains some empty cells ("Date" in row 22, and "Calories" in row 18 and 28).

The data set contains wrong format ("Date" in row 26).

The data set contains wrong data ("Duration" in row 7).

The data set contains duplicates (row 11 and 12).

* * *

* * *



In [6]:
#Load the CSV into a DataFrame:
# use to_string() to print the entire DataFrame.
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/WK10-Pandas Learner/Resources/data2.csv')

print(df.to_string())
#Keep an eye on the NaN value i.e. empty values NaN= Not a Number

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

In [7]:
#Load the CSV into a DataFrame:
# use to_string() to print the entire DataFrame.
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/WK10-Pandas Learner/Resources/data2.csv')

print(df.to_string())
#Keep an eye on the NaN value i.e. empty values NaN= Not a Number

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

In [ ]:
# Return a new Data Frame with no empty cells:

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/WK10-Pandas Learner/Resources/data2.csv')

new_df = df.dropna()

print(new_df.to_string())
#Notice in the result that some rows have been removed (row 18, 22 and 28).

#These rows had cells with empty values.

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

Replace Empty Values
--------------------

Another way of dealing with empty cells is to insert a _new_ value instead.

This way you do not have to delete entire rows just because of some empty cells.

The `fillna()` method allows us to replace empty cells with a value:

### Example
```
#Replace NULL values with the number 130:

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/WK10-pandas/Resources/data2.csv')

df.fillna(130, inplace = True)
```
[Try it Yourself »](https://www.w3schools.com/python/pandas/trypandas.asp?filename=demo_pandas_cleaning_fillna)



In [9]:
# Replace NULL values with the number 130:

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/WK10-Pandas Learner/Resources/data2.csv')

df.fillna(1400, inplace = True)
print(df.to_string())

#Notice in the result: empty cells got the value 130 (in row 18, 22 and 28).

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

### Replace Only For Specified Columns

The example above replaces all empty cells in the whole Data Frame.

To only replace empty values for one column, specify the _column name_ for the DataFrame:

### Example
```
#Replace NULL values in the "Calories" columns with the number 130:

import pandas as pd

df = pd.read_csv('data.csv')

df["Calories"].fillna(130, inplace = True)

print(df.to_string())

#This operation inserts 130 in empty cells in the "Calories" column (row 18 and 28).
```
[Try it Yourself »](https://www.w3schools.com/python/pandas/trypandas.asp?filename=demo_pandas_cleaning_fillna2)

* * *



In [13]:
import pandas as pd
from datetime import date

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/WK10-Pandas Learner/Resources/data2.csv')


df.info()
df["Date"].fillna(pd.to_datetime(df['Date']), inplace = True)
df["Calories"].fillna(130, inplace = True)

print(df.to_string())

#This operation inserts 130 in empty cells in the "Calories" column (row 18 and 28).

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  32 non-null     int64  
 1   Date      31 non-null     object 
 2   Pulse     32 non-null     int64  
 3   Maxpulse  32 non-null     int64  
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB
    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/

Replace Using Mean, Median, or Mode
-----------------------------------

A common way to replace empty cells, is to calculate the mean, median or mode value of the column.

Pandas uses the `mean()` `median()` and `mode()` methods to calculate the respective values for a specified column:

### Example: Calculate the MEAN, and replace any empty values with it:

```python
# 1. Bring in the pandas toolbox for data
import pandas as pd

# 2. Open the data book (CSV file)
df = pd.read_csv('/content/drive/MyDrive/WK10-pandas/Resources/data2.csv')

# 3. Find the average number of calories
x = df["Calories"].mean()  # Calculate the mean of the "Calories" column

# 4. Fill in missing calorie values with the average
df["Calories"].fillna(x, inplace=True)  # Replace empty cells with the mean

# 5. Show the updated data book
print(df.to_string())

# Notice: Empty calories now have the mean value (e.g., in rows 18 and 28)
```

**New lines explained:**

- **Calculate mean:** This line finds the average value in the "Calories" column, like finding the typical number of calories in a meal based on the available data.
- **Fill missing values:** This line looks for empty cells (like blank pages) in the "Calories" column and fills them with the average value calculated earlier, making the data more complete.

**Key points:**

- The code ensures that there are no empty values in the "Calories" column, which can be helpful for calculations and analysis that require complete data.
- It uses the mean to fill in missing values, which is a common technique to maintain consistency and avoid introducing biases.
- The final DataFrame has a complete "Calories" column, ready for further exploration and insights.




[Try it Yourself »](https://www.w3schools.com/python/pandas/trypandas.asp?filename=demo_pandas_cleaning_fillna_mean)

**Mean** = the average value (the sum of all values divided by number of values).

***

In [ ]:
# import pandas library
import pandas as pd

# read the csv file into a DataFrame
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/WK10-Pandas Learner/Resources/data2.csv')

# calculate the mean of the "Calories" column and assign it to x variable
x = df["Calories"].mean()

# replace any empty values in the "Calories" column with the mean value
df["Calories"].fillna(x, inplace = True)

# print the DataFrame as a string
print(df.to_string())

# as you can see in row 18 and 28, the empty values from "Calories" were replaced with the mean: 304.68

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130    409.10
1         60  '2020/12/02'    117       145    479.00
2         60  '2020/12/03'    103       135    340.00
3         45  '2020/12/04'    109       175    282.40
4         45  '2020/12/05'    117       148    406.00
5         60  '2020/12/06'    102       127    300.00
6         60  '2020/12/07'    110       136    374.00
7        450  '2020/12/08'    104       134    253.30
8         30  '2020/12/09'    109       133    195.10
9         60  '2020/12/10'     98       124    269.00
10        60  '2020/12/11'    103       147    329.30
11        60  '2020/12/12'    100       120    250.70
12        60  '2020/12/12'    100       120    250.70
13        60  '2020/12/13'    106       128    345.30
14        60  '2020/12/14'    104       132    379.30
15        60  '2020/12/15'     98       123    275.00
16        60  '2020/12/16'     98       120    215.20
17        60  '2020/12/17'  

### Example: Calculate the MEDIAN, and replace any empty values with it:


**Median** = the value in the middle, after you have sorted all values ascending.

```
#Calculate the MEDIAN, and replace any empty values with it:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/WK10-pandas/Resources/data2.csv')

x = df["Calories"].median()

df["Calories"].fillna(x, inplace = True)

print(df.to_string())

#As you can see in row 18 and 28, the empty values from "Calories" was replaced with the median: 291.2
```


[Try it Yourself »](https://www.w3schools.com/python/pandas/trypandas.asp?filename=demo_pandas_cleaning_fillna3)




* * *

In [ ]:
# Calculate the MEDIAN, and replace any empty values with it:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/WK10-Pandas Learner/Resources/data2.csv')

x = df["Calories"].median()

df["Calories"].fillna(x, inplace = True)

print(df.to_string())

# As you can see in row 18 and 28, the empty values from "Calories" was replaced with the median: 291.2

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

### Example: Calculate the MODE, and replace any empty values with it:

**Mode** = the value that appears most frequently.
```
#Calculate the MODE, and replace any empty values with it:

# Import pandas library
import pandas as pd

# Read the csv file into a DataFrame
df = pd.read_csv('data.csv')

# Calculate the mode of the "Calories" column
x = df["Calories"].mode()[0]

# Replace any empty values in the "Calories" column with the mode value
df["Calories"].fillna(x, inplace = True)

# Print the DataFrame as a string
print(df.to_string())

# As you can see in row 18 and 28, the empty value from "Calories" was replaced with the mode: 300.0

#Since there could be more than one mode value, the result is an array, and mode()[0] returns the first mode value.
#As you can see in row 18 and 28, the empty value from "Calories" was replaced with the mode: 300.0
```
[Try it Yourself »](https://www.w3schools.com/python/pandas/trypandas.asp?filename=demo_pandas_cleaning_fillna_mode)




In [ ]:
#Calculate the MODE, and replace any empty values with it:

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/WK10-Pandas Learner/Resources/data2.csv')

x = df["Calories"].mode()[0]

df["Calories"].fillna(x, inplace = True)

print(df.to_string())

#As you can see in row 18 and 28, the empty value from "Calories" was replaced with the mode: 300.0

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

#Cleaning Data of Wrong Format
* * *

Data of Wrong Format
--------------------

Cells with data of wrong format can make it difficult, or even impossible, to analyze data.

To fix it, you have two options: remove the rows, or convert all cells in the columns into the same format.

* * *

Convert Into a Correct Format
-----------------------------

In our Data Frame, we have two cells with the wrong format. Check out row 22 and 26, the 'Date' column should be a string that represents a date:
```

      Duration          Date  Pulse  Maxpulse  Calories
  0         60  '2020/12/01'    110       130     409.1
  1         60  '2020/12/02'    117       145     479.0
  2         60  '2020/12/03'    103       135     340.0
  3         45  '2020/12/04'    109       175     282.4
  4         45  '2020/12/05'    117       148     406.0
  5         60  '2020/12/06'    102       127     300.0
  6         60  '2020/12/07'    110       136     374.0
  7        450  '2020/12/08'    104       134     253.3
  8         30  '2020/12/09'    109       133     195.1
  9         60  '2020/12/10'     98       124     269.0
  10        60  '2020/12/11'    103       147     329.3
  11        60  '2020/12/12'    100       120     250.7
  12        60  '2020/12/12'    100       120     250.7
  13        60  '2020/12/13'    106       128     345.3
  14        60  '2020/12/14'    104       132     379.3
  15        60  '2020/12/15'     98       123     275.0
  16        60  '2020/12/16'     98       120     215.2
  17        60  '2020/12/17'    100       120     300.0
  18        45  '2020/12/18'     90       112       NaN
  19        60  '2020/12/19'    103       123     323.0
  20        45  '2020/12/20'     97       125     243.0
  21        60  '2020/12/21'    108       131     364.2
  22        45           NaN    100       119     282.0
  23        60  '2020/12/23'    130       101     300.0
  24        45  '2020/12/24'    105       132     246.0
  25        60  '2020/12/25'    102       126     334.5
  26        60      20201226    100       120     250.0
  27        60  '2020/12/27'     92       118     241.0
  28        60  '2020/12/28'    103       132       NaN
  29        60  '2020/12/29'    100       132     280.0
  30        60  '2020/12/30'    102       129     380.3
  31        60  '2020/12/31'     92       115     243.0
```
Let's try to convert all cells in the 'Date' column into dates.

Pandas has a `to_datetime()` method for this:

### Example: Convert to date:


```python
# 1. Import the pandas library
# - It's like bringing a special toolbox for working with data.
import pandas as pd

# 2. Load the data from a CSV file
# - Think of it like opening a book to read its contents.
df = pd.read_csv('/content/drive/MyDrive/WK10-pandas/Resources/data2.csv')

# 3. Convert a column to datetime format
# - Imagine having a column with dates written as text, but you want to treat them as actual dates.
df['Date'] = pd.to_datetime(df['Date'])

# 4. Display the entire DataFrame
# - Like showing the entire book on the screen.
print(df.to_string())
```

**Let's break it down further:**

- **Import pandas:** This line brings in the pandas library, giving you tools to work with data. It's like saying, "Let's use the pandas toolbox!"
- **Read CSV file:** This line opens a CSV file (a common format for storing data), like opening a book, and stores the information in a DataFrame, which is like a big table.
- **Convert to datetime:** This line focuses on a specific column called "Date" and changes its format to datetime, which is a special way of representing dates and times in Python, so you can do cool things with them later.
- **Print DataFrame:** This line shows the entire DataFrame on the screen, like opening the book and reading all its pages.

**Remember:**

- `df` is like a nickname for your DataFrame, making it easier to work with.
- `pd.to_datetime` is a special function from the pandas toolbox that helps you work with dates and times.
- `print` is a way to show something on the screen, like reading a book out loud.



[Try it Yourself »](https://www.w3schools.com/python/pandas/trypandas.asp?filename=demo_pandas_cleaning_to_datetime)

**Result:**
```

      Duration          Date  Pulse  Maxpulse  Calories
  0         60  '2020/12/01'    110       130     409.1
  1         60  '2020/12/02'    117       145     479.0
  2         60  '2020/12/03'    103       135     340.0
  3         45  '2020/12/04'    109       175     282.4
  4         45  '2020/12/05'    117       148     406.0
  5         60  '2020/12/06'    102       127     300.0
  6         60  '2020/12/07'    110       136     374.0
  7        450  '2020/12/08'    104       134     253.3
  8         30  '2020/12/09'    109       133     195.1
  9         60  '2020/12/10'     98       124     269.0
  10        60  '2020/12/11'    103       147     329.3
  11        60  '2020/12/12'    100       120     250.7
  12        60  '2020/12/12'    100       120     250.7
  13        60  '2020/12/13'    106       128     345.3
  14        60  '2020/12/14'    104       132     379.3
  15        60  '2020/12/15'     98       123     275.0
  16        60  '2020/12/16'     98       120     215.2
  17        60  '2020/12/17'    100       120     300.0
  18        45  '2020/12/18'     90       112       NaN
  19        60  '2020/12/19'    103       123     323.0
  20        45  '2020/12/20'     97       125     243.0
  21        60  '2020/12/21'    108       131     364.2
  22        45           NaT    100       119     282.0
  23        60  '2020/12/23'    130       101     300.0
  24        45  '2020/12/24'    105       132     246.0
  25        60  '2020/12/25'    102       126     334.5
  26        60  '2020/12/26'    100       120     250.0
  27        60  '2020/12/27'     92       118     241.0
  28        60  '2020/12/28'    103       132       NaN
  29        60  '2020/12/29'    100       132     280.0
  30        60  '2020/12/30'    102       129     380.3
  31        60  '2020/12/31'     92       115     243.0
```
As you can see from the result, the date in row 26 was fixed, but the empty date in row 22 got a NaT (Not a Time) value, in other words an empty value. One way to deal with empty values is simply removing the entire row.

* * *

* * *





In [ ]:
df['Date'] = pd.to_datetime(df['Date'])
print(df.to_string())

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        450 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90 

Removing Rows
-------------

The result from the converting in the example above gave us a NaT (Not a Time) value, which can be handled as a NULL value, and we can remove the row by using the `dropna()` method.

### Example: Remove rows with a NULL value in the "Date" column:


```python
# 1. Import the pandas library (toolbox for data)
import pandas as pd

# 2. Load the data from a CSV file (open the data book)
df = pd.read_csv('data.csv')

# 3. Convert the 'Date' column to datetime format (treat dates as dates)
df['Date'] = pd.to_datetime(df['Date'])

# 4. Remove rows with missing dates (tidy up the book)
df.dropna(subset=['Date'], inplace=True)

# 5. Display the updated DataFrame (show the cleaned book)
print(df.to_string())
```

**New line explained:**

- **Drop missing dates:** This line focuses on rows in the DataFrame where the "Date" column is empty (like missing pages in the book). It removes those rows to keep the data clean and organized.
    - `subset=['Date']` means "look only at the 'Date' column for missing values."
    - `inplace=True` means "make the changes directly to the DataFrame, like erasing missing pages from the book itself."

**Key points:**

- The code ensures that the "Date" column is in the proper format for working with dates and times.
- It removes rows with missing dates to avoid potential errors or misunderstandings in analysis.
- The final DataFrame contains only rows with valid dates, making it more reliable for further exploration.




[Try it Yourself »](https://www.w3schools.com/python/pandas/trypandas.asp?filename=demo_pandas_cleaning_dropnat)

* * *

In [ ]:
df.dropna(subset=['Date'], inplace = True)

print(df.to_string())

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        450 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90 

In [ ]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/WK10-Pandas Learner/Resources/data2.csv')

df['Date'] = pd.to_datetime(df['Date'])

df.dropna(subset=['Date'], inplace = True)

print(df.to_string())

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        450 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90 

#Pandas - Fixing Wrong Data
--------------------------

* * *

Wrong Data
----------

"Wrong data" does not have to be "empty cells" or "wrong format", it can just be wrong, like if someone registered "199" instead of "1.99".

Sometimes you can spot wrong data by looking at the data set, because you have an expectation of what it should be.

If you take a look at our data set, you can see that in row 7, the duration is 450, but for all the other rows the duration is between 30 and 60.

It doesn't have to be wrong, but taking in consideration that this is the data set of someone's workout sessions, we conclude with the fact that this person did not work out in 450 minutes.
```
      Duration          Date  Pulse  Maxpulse  Calories
  0         60  '2020/12/01'    110       130     409.1
  1         60  '2020/12/02'    117       145     479.0
  2         60  '2020/12/03'    103       135     340.0
  3         45  '2020/12/04'    109       175     282.4
  4         45  '2020/12/05'    117       148     406.0
  5         60  '2020/12/06'    102       127     300.0
  6         60  '2020/12/07'    110       136     374.0
**7        450  '2020/12/08'    104       134     253.3
  8         30  '2020/12/09'    109       133     195.1
  9         60  '2020/12/10'     98       124     269.0
  10        60  '2020/12/11'    103       147     329.3
  11        60  '2020/12/12'    100       120     250.7
  12        60  '2020/12/12'    100       120     250.7
  13        60  '2020/12/13'    106       128     345.3
  14        60  '2020/12/14'    104       132     379.3
  15        60  '2020/12/15'     98       123     275.0
  16        60  '2020/12/16'     98       120     215.2
  17        60  '2020/12/17'    100       120     300.0
  18        45  '2020/12/18'     90       112       NaN
  19        60  '2020/12/19'    103       123     323.0
  20        45  '2020/12/20'     97       125     243.0
  21        60  '2020/12/21'    108       131     364.2
  22        45           NaN    100       119     282.0
  23        60  '2020/12/23'    130       101     300.0
  24        45  '2020/12/24'    105       132     246.0
  25        60  '2020/12/25'    102       126     334.5
  26        60      20201226    100       120     250.0
  27        60  '2020/12/27'     92       118     241.0
  28        60  '2020/12/28'    103       132       NaN
  29        60  '2020/12/29'    100       132     280.0
  30        60  '2020/12/30'    102       129     380.3
  31        60  '2020/12/31'     92       115     243.0
```
How can we fix wrong values, like the one for "Duration" in row 7?

* * *

* * *

Replacing Values
----------------

One way to fix wrong values is to replace them with something else.

In our example, it is most likely a typo, and the value should be "45" instead of "450", and we could just insert "45" in row 7:

**Example**: Set "Duration" = 45 in row 7
----------

Set "Duration" = 45 in row 7:


```python
# 1. Import the pandas library (toolbox for data)
import pandas as pd

# 2. Load the data from a CSV file (open the data book)
df = pd.read_csv('data.csv')

# 3. Update a specific value in the DataFrame (make a change in the book)
df.loc[7, 'Duration'] = 45  # Change the value at row 7, column 'Duration' to 45

# 4. Display the updated DataFrame (show the modified book)
print(df.to_string())
```

**Explanation of 'df.loc[7, 'Duration'] = 45':**

- **Modify a value:** This line targets a specific cell in the DataFrame using its coordinates: row 7 (like the 7th page) and column 'Duration' (like a specific topic). It changes the value in that cell to 45, like correcting a mistake or updating information in the book.

**Key points:**

- The code demonstrates how to change individual values within a DataFrame, allowing you to make precise adjustments to the data.
- It uses the `.loc` method to locate specific cells based on their row and column labels.
- The final DataFrame reflects the updated value in the specified cell, ready for further analysis or usage.


[Try it Yourself »](https://www.w3schools.com/python/pandas/trypandas.asp?filename=demo_pandas_cleaning_wrong_data2)

* * *



In [ ]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/WK10-Pandas Learner/Resources/data2.csv')

df.loc[7,'Duration'] = 45

print(df.to_string())


    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7         45  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  


Loop through all values in the "Duration" column.
---------
For small data sets you might be able to replace the wrong data one by one, but not for big data sets.

To replace wrong data for larger data sets you can create some rules, e.g. set some boundaries for legal values, and replace any values that are outside of the boundaries.

### Example: Loop through all values in the "Duration" column.

Loop through all values in the "Duration" column.

If the value is higher than 120, set it to 120:


```python
# 1. Import the pandas library (toolbox for data)
import pandas as pd

# 2. Load the data from a CSV file (open the data book)
df = pd.read_csv('data.csv')

# 3. Check and adjust durations (make sure no activity lasts too long)
for x in df.index:  # Loop through each row in the DataFrame
    if df.loc[x, "Duration"] > 120:  # If the duration in a row is over 120
        df.loc[x, "Duration"] = 120  # Change it to 120 (set a maximum duration)

# 4. Display the updated DataFrame (show the adjusted book)
print(df.to_string())
```

**New section explained:**

- **Loop and cap durations:** This section introduces a loop that goes through each row in the DataFrame. For each row, it checks the "Duration" column. If the duration is higher than 120, it reduces it to 120, like setting a time limit for activities.

**Key points:**

- The code ensures that no duration in the DataFrame exceeds a specified value (120), which could be useful for data quality control or enforcing specific rules.
- It uses a loop and conditional statement to apply this rule systematically to every row in the DataFrame.
- The final DataFrame reflects the adjusted durations, with no values above the specified limit.



In [22]:
# 1. Import the pandas library (toolbox for data)
import pandas as pd

# 2. Load the data from a CSV file (open the data book)
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/WK10-Pandas Learner/Resources/data2.csv')

# 3. Check and adjust durations (make sure no activity lasts too long)
for x in df.index:  # Loop through each row in the DataFrame
    if df.loc[x, "Duration"] > 120:  # If the duration in a row is over 120
        df.loc[x, "Duration"] = 120  # Change it to 120 (set a maximum duration)


# 4. Display the updated DataFrame (show the adjusted book)
print(df.to_string())

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        120  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

Removing Rows
-------------

Another way of handling wrong data is to remove the rows that contains wrong data.

This way you do not have to find out what to replace them with, and there is a good chance you do not need them to do your analyses.

### Example: Delete rows where "Duration" is higher than 120

Delete rows where "Duration" is higher than 120:

```python
# 1. Import the pandas library (toolbox for data)
import pandas as pd

# 2. Load the data from a CSV file (open the data book)
df = pd.read_csv('data.csv')

# 3. Remove rows with long durations (filter out lengthy activities)
for x in df.index:  # Loop through each row in the DataFrame
    if df.loc[x, "Duration"] > 120:  # If the duration in a row is over 120
        df.drop(x, inplace=True)  # Remove that row from the DataFrame (like tearing out a page)

# 4. Display the updated DataFrame (show the shortened book)
print(df.to_string())
```

**Key parts explained:**

- **Remove rows:** Instead of adjusting values, this code now removes entire rows from the DataFrame if their duration exceeds 120. It's like filtering out activities that are too long.
- **`inplace=True`:** This argument within the `drop` method ensures that the changes are made directly to the original DataFrame, avoiding the creation of unnecessary copies.

**Key points:**

- The code filters the DataFrame to keep only rows with durations within a specified limit (120).
- It uses a loop and conditional statement to identify rows that meet the criteria for removal.
- The `drop` method is used to delete those rows, and `inplace=True` makes the changes permanent in the original DataFrame.
- The final DataFrame contains only rows with durations up to 120, ready for further analysis or usage based on this filtering.


[Try it Yourself »](https://www.w3schools.com/python/pandas/trypandas.asp?filename=demo_pandas_cleaning_wrong_data3)

* * *


In [ ]:
# 1. Import the pandas library (toolbox for data)
import pandas as pd

# 2. Load the data from a CSV file (open the data book)
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/WK10-Pandas Learner/Resources/data2.csv')

# 3. Remove rows with long durations (filter out lengthy activities)
for x in df.index:  # Loop through each row in the DataFrame
    if df.loc[x, "Duration"] > 120:  # If the duration in a row is over 120
        df.drop(x, inplace=True)  # Remove that row from the DataFrame (like tearing out a page)

# 4. Display the updated DataFrame (show the shortened book)
print(df.to_string())

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'  

#Pandas - Removing Duplicates
----------------------------

* * *

Discovering Duplicates
----------------------

Duplicate rows are rows that have been registered more than one time.
```

      Duration          Date  Pulse  Maxpulse  Calories
  0         60  '2020/12/01'    110       130     409.1
  1         60  '2020/12/02'    117       145     479.0
  2         60  '2020/12/03'    103       135     340.0
  3         45  '2020/12/04'    109       175     282.4
  4         45  '2020/12/05'    117       148     406.0
  5         60  '2020/12/06'    102       127     300.0
  6         60  '2020/12/07'    110       136     374.0
  7        450  '2020/12/08'    104       134     253.3
  8         30  '2020/12/09'    109       133     195.1
  9         60  '2020/12/10'     98       124     269.0
  10        60  '2020/12/11'    103       147     329.3
  **11        60  '2020/12/12'    100       120     250.7
  **12        60  '2020/12/12'    100       120     250.7
  13        60  '2020/12/13'    106       128     345.3
  14        60  '2020/12/14'    104       132     379.3
  15        60  '2020/12/15'     98       123     275.0
  16        60  '2020/12/16'     98       120     215.2
  17        60  '2020/12/17'    100       120     300.0
  18        45  '2020/12/18'     90       112       NaN
  19        60  '2020/12/19'    103       123     323.0
  20        45  '2020/12/20'     97       125     243.0
  21        60  '2020/12/21'    108       131     364.2
  22        45           NaN    100       119     282.0
  23        60  '2020/12/23'    130       101     300.0
  24        45  '2020/12/24'    105       132     246.0
  25        60  '2020/12/25'    102       126     334.5
  26        60      20201226    100       120     250.0
  27        60  '2020/12/27'     92       118     241.0
  28        60  '2020/12/28'    103       132       NaN
  29        60  '2020/12/29'    100       132     280.0
  30        60  '2020/12/30'    102       129     380.3
  31        60  '2020/12/31'     92       115     243.0
```
By taking a look at our test data set, we can assume that <mark>row 11 and 12</mark> are duplicates.

To discover duplicates, we can use the `duplicated()` method.

The `duplicated()` method returns a Boolean values for each row:

**Example**: Returns `True` for every row that is a duplicate, otherwise `False`:


```python
# 1. Import the pandas library (toolbox for data)
import pandas as pd

# 2. Load the data from a CSV file (open the data book)
df = pd.read_csv('data.csv')

# 3. Check for duplicate rows (find identical pages in the book)
print(df.duplicated())
```

**`duplicated()` method:**

- **Identify duplicates:** This line uses the `duplicated` method to check for rows in the DataFrame that are completely identical to previous rows. It's like noticing pages in a book that have the same exact content.

**Output:**

- The `print(df.duplicated())` statement will display a Series of Boolean values (True/False) for each row in the DataFrame.
    - True indicates that a row is a duplicate of a previous row.
    - False means the row is unique.

**Key points:**

- The code helps you identify potential data quality issues or redundancies in the DataFrame.
- It's often used as a preliminary step before further analysis or cleaning to ensure data accuracy and consistency.
- The output can be used to filter out duplicates or investigate their causes.


* * *


In [ ]:
# 1. Import the pandas library (toolbox for data)
import pandas as pd

# 2. Load the data from a CSV file (open the data book)
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/WK10-Pandas Learner/Resources/data2.csv')

# 3. Check for duplicate rows (find identical pages in the book)
print(df.duplicated())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
dtype: bool



Removing Duplicates
-------------------

To remove duplicates, use the `drop_duplicates()` method.

**Remember:** The `(inplace = True)` will make sure that the method does NOT return a _new_ DataFrame, but it will remove all duplicates from the _original_ DataFrame.

**Example: Removing Duplicates Altogether**

```python
# 1. Import the pandas library (toolbox for data)
import pandas as pd

# 2. Load the data from a CSV file (open the data book)
df = pd.read_csv('data.csv')

# 3. Remove duplicate rows (keep only unique pages in the book)
df.drop_duplicates(inplace=True)

# 4. Display the updated DataFrame (show the book without duplicates)
print(df.to_string())
```

**New line explained:**

- **Remove duplicates:** This line uses the `drop_duplicates` method to eliminate any rows that are exact copies of previous rows. It's like removing extra copies of pages in the book to keep only the unique content.
- **`inplace=True`:** This argument ensures that the duplicate rows are removed directly from the original DataFrame, making the changes permanent.

**Key points:**

- The code cleans the DataFrame by removing redundant information, ensuring that each row represents unique data.
- It's often used to improve data quality, reduce file size, and avoid potential biases in analysis caused by duplicate entries.
- The final DataFrame contains only unique rows, ready for further exploration and analysis without the need to worry about duplicates.


* * *





In [ ]:
# 1. Import the pandas library (toolbox for data)
import pandas as pd

# 2. Load the data from a CSV file (open the data book)
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/WK10-Pandas Learner/Resources/data2.csv)

# 3. Remove duplicate rows (keep only unique pages in the book)
df.drop_duplicates(inplace=True)

# 4. Display the updated DataFrame (show the book without duplicates)
print(df.to_string())

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
18        45  '2020/12/18'  

Test Yourself With Exercises
----------------------------

Exercise:
---------

Insert the correct syntax for removing rows with empty cells.

[Start the Exercise](https://www.w3schools.com/python/pandas/exercise.asp?filename=exercise_cleaning1)
